spring.application.name=Rental Payment

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

management.endpoints.web.exposure.include=*

#spring.datasource.url=jdbc:h2:./.db/rental_payment_saga_db;AUTO_SERVER=TRUE
spring.jpa.hibernate.ddl-auto=update

axon.serializer.general=jackson

#logging.level.org.springframework.boot=INFO
