spring.application.name=gateway
server.port=8760

# Eureka-Konfiguration
#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.serviceUrl.defaultZone=http://registry:8761/eureka/
eureka.client.registerWithEureka=false
eureka.client.fetchRegistry=true
eureka.client.registry-fetch-interval-seconds=10

eureka.client.healthcheck.enabled=true

# Gateway-Routen

# Route 1: Service erreichbar unter /service/
spring.cloud.gateway.routes[0].id=service
spring.cloud.gateway.routes[0].uri=lb://service
spring.cloud.gateway.routes[0].predicates[0]=Path=/service/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1
#
## Route 2: Eureka-UI ueber das Gateway erreichbar
#spring.cloud.gateway.routes[1].id=eureka
#spring.cloud.gateway.routes[1].uri=http://registry:8761
#spring.cloud.gateway.routes[1].predicates[0]=Path=/eureka/**
#
## Route 3: Falls direkte Kommunikation mit Registry gewuenscht ist
#spring.cloud.gateway.routes[2].id=registry
#spring.cloud.gateway.routes[2].uri=lb://registry
#spring.cloud.gateway.routes[2].predicates[0]=Path=/registry/**
#spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1

# Actuator-Endpunkte aktivieren (optional)
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

logging.level.com.netflix.eureka=INFO
logging.level.com.netflix.discovery=INFO
