spring.application.name=gateway

server.port=8080

logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG
logging.level.org.springframework.cloud.gateway=DEBUG

# ? Allgemeine Gateway Konfiguration: Alle Flows
spring.security.oauth2.client.registration.gateway.provider=uaa
spring.security.oauth2.client.registration.gateway.client-id=gateway
spring.security.oauth2.client.registration.gateway.client-secret=secret

## ? Konfiguration: Client Credentials Flow
#spring.security.oauth2.client.registration.gateway.authorization-grant-type=client_credentials
#spring.security.oauth2.client.registration.gateway.scope=resource.read,uaa.user

## ? Konfiguration: Implict Flow
#spring.security.oauth2.client.registration.gateway.authorization-grant-type=implicit
#spring.security.oauth2.client.registration.gateway.redirect-uri=http://localhost:8080/login/oauth2/code/gateway
#spring.security.oauth2.client.provider.uaa.authorization-uri=http://localhost:8070/oauth/authorize
#spring.security.oauth2.client.provider.uaa.user-info-uri=http://localhost:8070/userinfo
#spring.security.oauth2.client.provider.uaa.user-name-attribute=sub
#spring.security.oauth2.client.registration.gateway.scope=clients.read,clients.secret,clients.write,uaa.admin,resource.read,resource.write

# ? Konfiguration: Authorization Code Flow
spring.security.oauth2.client.registration.gateway.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.gateway.redirect-uri=http://localhost:8080/login/oauth2/code/gateway
spring.security.oauth2.client.provider.uaa.authorization-uri=http://localhost:8070/oauth/authorize
spring.security.oauth2.client.provider.uaa.user-info-uri=http://uaa:8080/userinfo
spring.security.oauth2.client.provider.uaa.user-name-attribute=sub

# ? OAuth2 Provider UAA
spring.security.oauth2.client.provider.uaa.token-uri=http://uaa:8080/oauth/token
spring.security.oauth2.client.provider.uaa.jwk-set-uri=http://uaa:8080/token_keys

# ? Resource Server JWT-Validierung (Resource-Server erwartet Tokens von UAA)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://uaa:8080/oauth/token
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://uaa:8080/token_keys




