management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

management.health.circuitbreakers.enabled=true
management.health.ratelimiters.enabled=true

#CIRCUIT BREAKER
resilience4j.circuitbreaker.instances.randomCode.slidingWindowSize=3
resilience4j.circuitbreaker.instances.randomCode.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.randomCode.minimumNumberOfCalls=3
resilience4j.circuitbreaker.instances.randomCode.failureRateThreshold=50
resilience4j.circuitbreaker.instances.randomCode.waitDurationInOpenState=2000
resilience4j.circuitbreaker.instances.randomCode.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.randomCode.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.instances.randomCode.eventConsumerBufferSize=10
spring.cloud.circuitbreaker.resilience4j.disable-time-limiter=true


# TIME LIMITER
#logging.level.org.springframework.cloud.circuitbreaker.demo.resilience4jcircuitbreakerdemo.circuitbreaker=WARN
#spring.cloud.circuitbreaker.resilience4j.disable-time-limiter=false
#resilience4j.timelimiter.instances.timedelay.timeout-duration=2s

# RATE LIMITER
#resilience4j.ratelimiter.instances.myRateLimiter.limit-for-period=3
#resilience4j.ratelimiter.instances.myRateLimiter.limit-refresh-period=1s
#resilience4j.ratelimiter.instances.myRateLimiter.timeout-duration=0

# RATE LIMITER V2
#resilience4j.ratelimiter.instances.myRateLimiter.limit-for-period=3
#resilience4j.ratelimiter.instances.myRateLimiter.limit-refresh-period=1s
#resilience4j.ratelimiter.instances.myRateLimiter.timeout-duration=500ms


# BULKHEAD
#resilience4j.bulkhead.instances.myBulkhead.max-concurrent-calls=3
#resilience4j.bulkhead.instances.myBulkhead.max-wait-duration=1000ms


# ALLES ZUSAMMEN
#resilience4j.bulkhead.instances.taskBH.max-concurrent-calls=5
#resilience4j.bulkhead.instances.taskBH.max-wait-duration=1000ms
#resilience4j.circuitbreaker.instances.taskCB.slidingWindowSize=3
#resilience4j.circuitbreaker.instances.taskCB.slidingWindowType=COUNT_BASED
#resilience4j.circuitbreaker.instances.taskCB.minimumNumberOfCalls=3
#resilience4j.circuitbreaker.instances.taskCB.failureRateThreshold=50
#resilience4j.circuitbreaker.instances.taskCB.waitDurationInOpenState=2000
#resilience4j.circuitbreaker.instances.taskCB.permittedNumberOfCallsInHalfOpenState=3
#resilience4j.circuitbreaker.instances.taskCB.automaticTransitionFromOpenToHalfOpenEnabled=true
#resilience4j.circuitbreaker.instances.taskCB.eventConsumerBufferSize=10
#resilience4j.timelimiter.instances.taskCB.timeout-duration=1000ms
